"""adiciona campo tipo em veiculos

Revision ID: 212594239762
Revises: a51cf5f25f7d
Create Date: 2026-04-26 16:49:56.911773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '212594239762'
down_revision: Union[str, Sequence[str], None] = 'a51cf5f25f7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('veiculos', sa.Column('tipo', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('veiculos', 'tipo')
    # ### end Alembic commands ###
