"""adiciona tabela veiculos e ajustes

Revision ID: a51cf5f25f7d
Revises: 88a53f59a972
Create Date: 2026-04-26 16:33:19.445017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a51cf5f25f7d'
down_revision: Union[str, Sequence[str], None] = '88a53f59a972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
