"""criacao_tabelas_iniciais

Revision ID: fa740126164b
Revises: 
Create Date: 2026-04-23 23:45:01.152873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa740126164b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('rua', sa.String(length=200), nullable=True),
    sa.Column('numero', sa.String(length=10), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('ponto_referencia', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_documento'), 'clientes', ['documento'], unique=True)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('filiais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filiais_id'), 'filiais', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('perfil', sa.String(length=20), nullable=True),
    sa.Column('filial_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['filial_id'], ['filiais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('entregas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cupom_fiscal', sa.String(length=50), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('filial_id', sa.Integer(), nullable=True),
    sa.Column('operador_id', sa.Integer(), nullable=True),
    sa.Column('entregador_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_aceite', sa.DateTime(), nullable=True),
    sa.Column('data_finalizacao', sa.DateTime(), nullable=True),
    sa.Column('rua', sa.String(length=200), nullable=True),
    sa.Column('numero', sa.String(length=10), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['entregador_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['filial_id'], ['filiais.id'], ),
    sa.ForeignKeyConstraint(['operador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entregas_cupom_fiscal'), 'entregas', ['cupom_fiscal'], unique=False)
    op.create_index(op.f('ix_entregas_id'), 'entregas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entregas_id'), table_name='entregas')
    op.drop_index(op.f('ix_entregas_cupom_fiscal'), table_name='entregas')
    op.drop_table('entregas')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_filiais_id'), table_name='filiais')
    op.drop_table('filiais')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_documento'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
